# Generated by Django 4.2.3 on 2023-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='hobby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
