# Generated by Django 4.2.3 on 2023-07-11 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('date_openning', models.DateField()),
            ],
        ),
    ]
